#!/bin/bash

brew install aom
brew install aribb24
brew install ast-grep
brew install augeas
brew install bash
brew install bat
brew install bc
brew install brotli
brew install btop
brew install c-ares
brew install ca-certificates
brew install cairo
brew install certbot
brew install certifi
brew install cffi
brew install cfitsio
brew install cgif
brew install chafa
brew install cjson
brew install cli11
brew install cmake
brew install coreutils
brew install cowsay
brew install cryptography
brew install dav1d
brew install devcontainer
brew install dialog
brew install diff-so-fancy
brew install eza
brew install fd
brew install ffmpeg
brew install ffmpegthumbnailer
brew install fftw
brew install flac
brew install fmt
brew install fontconfig
brew install freetype
brew install frei0r
brew install fribidi
brew install fzf
brew install gawk
brew install gcc
brew install gdk-pixbuf
brew install gettext
brew install gh
brew install ghostscript
brew install giflib
brew install git
brew install git-delta
brew install gitleaks
brew install glab
brew install glib
brew install gmp
brew install gnu-sed
brew install gnupg
brew install gnutls
brew install go
brew install gpgme
brew install graphite2
brew install harfbuzz
brew install hdf5
brew install helix
brew install helm
brew install helmsman
brew install highway
brew install htop
brew install hwloc
brew install icu4c@76
brew install icu4c@77
brew install imagemagick
brew install imath
brew install isl
brew install jasper
brew install jbig2dec
brew install jpeg-turbo
brew install jpeg-xl
brew install jq
brew install k6
brew install kubernetes-cli
brew install lame
brew install lazydocker
brew install lazygit
brew install leptonica
brew install libaec
brew install libarchive
brew install libass
brew install libassuan
brew install libavif
brew install libb2
brew install libbluray
brew install libde265
brew install libdeflate
brew install libdicom
brew install libevent
brew install libexif
brew install libgcrypt
brew install libgpg-error
brew install libgit2
brew install libheif
brew install libidn
brew install libidn2
brew install libimagequant
brew install libksba
brew install liblqr
brew install libmatio
brew install libmicrohttpd
brew install libmpc
brew install libnghttp2
brew install libogg
brew install libomp
brew install libpng
brew install libraw
brew install librsvg
brew install libsamplerate
brew install libsixel
brew install libsndfile
brew install libsodium
brew install libsoxr
brew install libspng
brew install libssh
brew install libssh2
brew install libtasn1
brew install libtiff
brew install libtool
brew install libunibreak
brew install libunistring
brew install libusb
brew install libuv
brew install libvidstab
brew install libvmaf
brew install libvorbis
brew install libvpx
brew install libx11
brew install libxau
brew install libxcb
brew install libxdmcp
brew install libxext
brew install libxml2
brew install libxrender
brew install libyaml
brew install little-cms2
brew install llvm
brew install llvm@19
brew install lpeg
brew install lua
brew install lua-language-server
brew install luajit
brew install luarocks
brew install luv
brew install lz4
brew install lzo
brew install m4
brew install maven
brew install mbedtls
brew install mozjpeg
brew install mpdecimal
brew install mpfr
brew install mpg123
brew install ncurses
brew install neofetch
brew install neovim
brew install nettle
brew install nlohmann-json
brew install node
brew install nowplaying-cli
brew install npth
brew install nspr
brew install nss
brew install nvm
brew install oniguruma
brew install open-mpi
brew install opencore-amr
brew install openexr
brew install openjdk
brew install openjpeg
brew install openslide
brew install openssl@3
brew install opus
brew install p11-kit
brew install pango
brew install pcre2
brew install pinentry
brew install pinentry-mac
brew install pipx
brew install pixman
brew install pkgconf
brew install pmix
brew install poppler
brew install pycparser
brew install python-packaging
brew install python-setuptools
brew install python@3.12
brew install python@3.13
brew install range-v3
brew install rav1e
brew install readline
brew install ripgrep
brew install rubberband
brew install ruby
brew install rust
brew install rust-analyzer
brew install screenresolution
brew install sdl2
brew install sesh
brew install sevenzip
brew install shared-mime-info
brew install slides
brew install snappy
brew install sops
brew install spdlog
brew install speex
brew install sqlite
brew install srt
brew install starship
brew install stow
brew install svt-av1
brew install tbb
brew install tesseract
brew install thefuck
brew install theora
brew install tlrc
brew install tmux
brew install tokei
brew install tree-sitter
brew install trivy
brew install trufflehog
brew install unar
brew install unbound
brew install unibilium
brew install utf8proc
brew install uthash
brew install vips
brew install viu
brew install webp
brew install wget
brew install x264
brew install x265
brew install xorgproto
brew install xvid
brew install xz
brew install yazi
brew install yq
brew install z3
brew install zimg
brew install zoxide
brew install zsh-autosuggestions
brew install zstd

brew install jstkdng/programs/ueberzugpp 
brew install daveshanley/vacuum/vacuum
