# ███████╗████████╗ █████╗ ██████╗ ███████╗██╗  ██╗██╗██████╗
# ██╔════╝╚══██╔══╝██╔══██╗██╔══██╗██╔════╝██║  ██║██║██╔══██╗
# ███████╗   ██║   ███████║██████╔╝███████╗███████║██║██████╔╝
# ╚════██║   ██║   ██╔══██║██╔══██╗╚════██║██╔══██║██║██╔═══╝
# ███████║   ██║   ██║  ██║██║  ██║███████║██║  ██║██║██║
# ╚══════╝   ╚═╝   ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═╝╚═╝
# The minimal, blazing-fast, and infinitely customizable prompt
# https://starship.rs

"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 3600

[character]
success_symbol = "[](white)"
error_symbol = "[](red)"
vicmd_symbol = "[](green)"

[directory]
style = "blue bold"

[package]
disabled = true

[username]
disabled = true

[hostname]
disabled = true

[aws]
disabled = true

[docker_context]
disabled = true

[git_branch]
disabled = false

[git_commit]
disabled = true

[git_state]
disabled = false

[git_metrics]
disabled = false

[git_status]
disabled = false
