# This is how to make it work: the /etc/keyd/default.conf file 
# should be a symlink to the ~/.config/keyd/default.conf file. 
# sudo rm -rf /etc/keyd
# sudo ln -s ~/.config/keyd /etc
#
# After any modificatinos here, it is needed to restart the keyd service:
# sudo systemctl restart keyd

[ids]
*

[main]
# CapsLock acts as Escape on tap, Control on hold
capslock = overload(control, esc)
y = z
z = y

# (Optional) Map physical Esc to `pause` key so we can later remap it to the XCompose key in `~/.config/hypr/input.conf# esc = pause
