return {
  "mason-org/mason.nvim",
  cmd = "Mason",
  build = ":MasonUpdate",
  opts_extend = { "ensure_installed" },
  opts = {
    ensure_installed = {
      "angular-language-server",
      "bash-language-server",
      "biome",
      "copilot-language-server",
      "css-lsp",
      "css-variables-language-server",
      "cssmodules-language-server",
      "docker-compose-language-service",
      "dockerfile-language-server",
      "emmet-language-server",
      "eslint-lsp",
      "html-lsp",
      "json-lsp",
      "lua-language-server",
      "markdown-toc",
      "markdownlint-cli2",
      "marksman",
      "prettier",
      "prettierd",
      "shellcheck",
      "shfmt",
      "stylelint",
      "stylelint-lsp",
      "stylua",
      "tailwindcss-language-server",
      "vtsls",
      "yaml-language-server",
    },
  },
}
