general.import = ["~/.config/omarchy/current/theme/alacritty.toml"]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "JetBrainsMono Nerd Font" }
bold = { family = "JetBrainsMono Nerd Font" }
italic = { family = "JetBrainsMono Nerd Font" }
size = 12
offset.x = 0
offset.y = 4

[window]
padding.x = 14
padding.y = 14
decorations = "None"

[keyboard]
bindings = [
  { key = "Insert", mods = "Shift", action = "Paste" },
  { key = "Insert", mods = "Control", action = "Copy" },
  { key = "N", mods = "Control", chars = "\u001b[B" },   # Ctrl+N for down
  { key = "P", mods = "Control", chars = "\u001b[A" },   # Ctrl+P for up
]

[terminal]
osc52 = "CopyPaste"
